name: Back up simplifier source code

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Set today
        id: today
        run: echo "TODAY=$(date)" >> $GITHUB_OUTPUT

      - name: Set branch name
        id: branch-name
        run: echo "BRANCH=$(echo ${{ steps.today.outputs.TODAY }} | tr -d '[:space:]' | tr -d ':')" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          head -n 2 README.md > README1.md
          echo "Updated at: $(date)" >> README1.md
          mv README1.md README.md

      - name: Download and commit simplifier source code
        run: |
          cd backup
          rm -r *
          wget ${{ vars.SIMPLIFIER_ADDRESS }} -O export.zip
          unzip -u -o export.zip
          mv export.zip ..
          cd ..

      - name: Commit report
        run: |
          git config --global user.name '{{ vars.COMITTER_NAME }}'
          git config --global user.email '${{ secrets.COMITTER }}'
          git checkout -b ${{ steps.branch-name.outputs.BRANCH }}
          git add -A
          git commit -m "${{ steps.today.outputs.TODAY }}"
          git push origin ${{ steps.branch-name.outputs.BRANCH }}

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: '${{ steps.today.outputs.TODAY }}'
          branch: main
          delete-branch: true
          title: '${{ steps.today.outputs.TODAY }}'
          body: |
            Auto Generated Pull Request
            This PR creates a back up of the Simplifier export at ${{ vars.SIMPLIFIER_ADDRESS }}
      
      - name: Merge Pull Request (Conditional)
        if: github.event.client_payload.merge == true
        uses: actions/github-script@v6
        with: 
          github-token: ${{secrets.TOKEN}}
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.create-pr.outputs.pull-request-number }}
            });

